version: 2
updates:
  - package-ecosystem: nuget
    directory: /starter/csharp
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /starter/python
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /starter/typescript
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
